name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update &&
        sudo apt-get install curl \
          libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev \
          libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
          libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
        #curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Linux.zip" -o pluginval.zip &&
        #unzip pluginval.zip
    - name: build
      run: cd Builds/LinuxMakefile && make
    #- name: validate with pluginval ## Pluginval generates Segfaults on the CI runner
    #  run: |
    #    plugin=($(find . -iname "*.vst3")) &&
    #    ./pluginval --validate-in-process "${plugin[0]}" || exit 1
