name: Plugin build (Linux x64) 

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update &&
        sudo apt-get install \
          libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev \
          libfreetype6-dev
    - name: build
      run: >
        cd Builds/LinuxMakefile && make CONFIG=Release &&
        mkdir Artifacts && mv build/Arpligner Artifacts && mv build/Arpligner.vst3 Artifacts && mv build/Arpligner.lv2 Artifacts
    - name: upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: arpligner-build-linux
        path: Builds/LinuxMakefile/Artifacts

    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: Builds/LinuxMakefile/Artifacts/*
        generate_release_notes: true
